return {}
-- return {
-- 	"mistricky/codesnap.nvim",
-- 	build = "make",
-- 	opts = {
-- 		save_path = "~/Pictures/codesnaps/",
-- 		code_font_family = "Fira Sans",
-- 		bg_padding = 0,
-- 		watermark = "",
-- 	},
-- }
